// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1H9uAtpQVyzs-GiwNYxtNwm1u0pekbKQ',
    appId: '1:396776854132:web:5a7cc3ff65948f89afb721',
    messagingSenderId: '396776854132',
    projectId: 'finalproject-5949b',
    authDomain: 'finalproject-5949b.firebaseapp.com',
    storageBucket: 'finalproject-5949b.appspot.com',
    measurementId: 'G-KFB4M8T1H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCx-aOKtcK1bLKe6lT4oMORw2VPMLfLvo',
    appId: '1:396776854132:android:b43cebafdce012feafb721',
    messagingSenderId: '396776854132',
    projectId: 'finalproject-5949b',
    storageBucket: 'finalproject-5949b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUTvEol4kgVIDpP8zzXa0aRKngnJulMZM',
    appId: '1:396776854132:ios:bd9c85cafa215ca0afb721',
    messagingSenderId: '396776854132',
    projectId: 'finalproject-5949b',
    storageBucket: 'finalproject-5949b.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUTvEol4kgVIDpP8zzXa0aRKngnJulMZM',
    appId: '1:396776854132:ios:bd9c85cafa215ca0afb721',
    messagingSenderId: '396776854132',
    projectId: 'finalproject-5949b',
    storageBucket: 'finalproject-5949b.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1H9uAtpQVyzs-GiwNYxtNwm1u0pekbKQ',
    appId: '1:396776854132:web:02a8d08ad9235f2fafb721',
    messagingSenderId: '396776854132',
    projectId: 'finalproject-5949b',
    authDomain: 'finalproject-5949b.firebaseapp.com',
    storageBucket: 'finalproject-5949b.appspot.com',
    measurementId: 'G-LPMCL67876',
  );
}
